# Generated by Django 5.1.7 on 2025-03-22 03:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_date_of_birth_user_designation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('WRK', 'Working'), ('AVL', 'Available'), ('AST', 'Assist'), ('ABS', 'Absent')], default='WRK', max_length=5),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_color',
            field=models.CharField(default='#62983f', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='reporting_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teams', to=settings.AUTH_USER_MODEL),
        ),
    ]
