# Generated by Django 5.1.7 on 2025-03-22 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_assigned_to_user_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_color',
            field=models.CharField(default='#43aa0f', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('WRK', 'Working'), ('BKD', 'Booked'), ('AVL', 'Available'), ('AST', 'Assist'), ('ABS', 'Absent')], default='WRK', max_length=5),
        ),
    ]
