# Generated by Django 5.1.7 on 2025-03-23 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_profile_color_alter_user_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='assigned_till',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_color',
            field=models.CharField(default='#a84a3d', max_length=10),
        ),
    ]
