# Generated by Django 5.1.7 on 2025-03-23 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_assigned_till_alter_user_profile_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_pool',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_color',
            field=models.CharField(default='#600674', max_length=10),
        ),
    ]
